variables:
    APP_BUCKET:
        default: null
        description: the name of the bucket from which we should pull the app
        overrides: null
        required: true
    APP_NAME:
        default: null
        description: the name of the app to launch
        overrides: null
        required: true
    APP_DNS_PREFIX:
        default: null
        description: the dns entry to create for the app
        overrides: null
        required: true
        type: null
    DNS_ZONE:
        default: null
        description: the dns entry for the zone (i.e. example.com)
        overrides: null
        required: true
        type: null
    APP_SSH_KEY_NAME:
        default: null
        description: What key should the app instance be launched with?
        overrides: null
        required: true
        type: null
    APP_BUCKET_PATH:
        default: null
        description: the path within APP_BUCKET from which we should pull the app
        overrides: null
        required: true
    APP_ARCHIVE_NAME:
        default: null
        description: the name of the .tar.gz file which contains your app code
        overrides: null
        required: true
    INSTALL_REDIS:
        default: false
        description: whether to install and run redis or not          
        overrides: null
    VPC_NAME:
        required: true
        description: the name of the VPC
        default: vpc
    VPC_OCTETS:
        default: 10.11.0.0
        description: null
        overrides: null
        required: true
        type: null
    PRIVATE_ROUTE_NAME:
        required: true
        description: the name to give to the private route
        default: private-route
    PRIVATE_SUBNET_NAME:
        default: private-subnet
        description: null
        overrides: null
        required: true
        type: null
    APP_BUCKET_REGION:
        default: us-east-1
        description: the region where there app bucket was created
        overrides: null
        required: true
    PUBLIC_ROUTE_NAME:
        required: true
        description: the name to give to the public route
        default: public-route
    PUBLIC_SUBNET_NAME:
        default: public-subnet
        description: null
        overrides: null
        required: true
        type: null
    VPN_ACCESS_CIDRS:
        default:
            - 0.0.0.0/0
        description: null
        overrides: null
        required: true
        type: array
    ELB_TYPE:
        default: public
        description: one of public/internal
        overrides: null
        required: true
    ELB_SUBNET_NAME:
        default: public-subnet
        description: the name of the subnet the elb should created in (should correspond to ELB_TYPE)
        overrides: null
        required: true
    ELB_PROXY_PORT:
        default: 80
        description: "elb proxy port -- this will be forwarded to the same port on elb, but forwarded to https by nginx config"
        overrides: null
        required: true
    ELB_SSL_PROXY_PORT:
        default: 443
        description: elb ssl proxy port -- this will be forwarded to ELB_HEALTH_CHECK_PORT by elb (install ssl cert on this listener)
        overrides: null
        required: true
    ELB_HEALTH_CHECK_PORT:
        default: 1443
        description: elb healthcheck port -- nginx listens to this port and forwards to node
        overrides: null
        required: true
    VPN_SSH_ACCESS_CIDRS:
        default:
            - 10.0.0.0/8
        description: The cidrs from where you should be able to ssh in
        overrides: null
        required: true
        type: array
    APP_INSTANCE_TYPE:
        default: t2.micro
        description: null
        overrides: null
        required: true
        type: null
    TIMEZONE:
        default: America/Chicago
        value: America/Chicago
        description: the timezone the servers should come up in
        overrides: null
        required: true
        type: null
    ELB_NAME:
        default: "COMPOSITE::coreo_aws_ec2_elb.dev-elb.dns_name"
        required: true
        descripiton: comma seperated list of the private subnet ids
    APP_PORT:
        default: 3000
        description: upstream app port
        overrides: null
        required: true
    REGION:
        default: "PLAN::region"
        description: the region we are launching in
        overrides: null
        required: true
        type: string
    APP_AMI_ID:
        description: the ami id of the vpn
        switch: "PLAN::region"
        cases:
            us-east-1: ami-1ecae776
            us-west-1: ami-d114f295
            us-west-2: ami-e7527ed7
            eu-west-1: ami-a10897d6
            eu-central-1: ami-a8221fb5
            ap-southeast-1: ami-68d8e93a
            ap-northeast-1: ami-cbf90ecb
            ap-southeast-2: ami-fd9cecc7
            sa-east-1: ami-b52890a8
        type: case
    DATADOG_KEY:
        default: null
        value: null
        description: "If you have a datadog key, enter it here and we will install the agent"
        overrides: null
        required: false
    APP_STARTUP_ARGS:
        default: null
        description: the environment string to pass to node on start
        overrides: null
        required: false
